# Generated by Django 3.2.5 on 2022-11-03 09:57

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(default=None, max_length=20, verbose_name='Bus Name')),
                ('bus_number', models.CharField(default=None, max_length=10, verbose_name='Bus Number')),
                ('route', models.CharField(max_length=50, verbose_name='Route')),
                ('arrival_time', models.DateTimeField(verbose_name='Arrival Timing')),
                ('departure_time', models.DateTimeField(verbose_name='Departure Timing')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seat.seat')),
            ],
            options={
                'verbose_name': 'Bus',
                'db_table': 'Bus',
            },
        ),
    ]
