# Generated by Django 3.2.5 on 2022-11-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='seat',
        ),
    ]
