# Generated by Django 3.2.5 on 2022-11-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_name', models.CharField(default=None, max_length=5, verbose_name='Seat')),
                ('seat_number', models.CharField(default=None, max_length=5, verbose_name='Seat Number')),
            ],
            options={
                'verbose_name': 'seat',
                'db_table': 'seat',
            },
        ),
    ]
