# Generated by Django 3.2.5 on 2022-11-03 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_remove_bus_seat'),
        ('seat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_bus', to='bus.bus'),
        ),
    ]
